
# This file is automatically generated, you probably don't want to edit this

flexhistOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "flexhistOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            binWidthType = "default",
            binWidth = 0.5,
            binLowerLimit = NULL, ...) {

            super$initialize(
                package="flexhist",
                name="flexhist",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..binWidthType <- jmvcore::OptionList$new(
                "binWidthType",
                binWidthType,
                options=list(
                    "default",
                    "manual",
                    "sturges"),
                default="default")
            private$..binWidth <- jmvcore::OptionNumber$new(
                "binWidth",
                binWidth,
                default=0.5,
                min=0)
            private$..binLowerLimit <- jmvcore::OptionNumber$new(
                "binLowerLimit",
                binLowerLimit)

            self$.addOption(private$..dep)
            self$.addOption(private$..binWidthType)
            self$.addOption(private$..binWidth)
            self$.addOption(private$..binLowerLimit)
        }),
    active = list(
        dep = function() private$..dep$value,
        binWidthType = function() private$..binWidthType$value,
        binWidth = function() private$..binWidth$value,
        binLowerLimit = function() private$..binLowerLimit$value),
    private = list(
        ..dep = NA,
        ..binWidthType = NA,
        ..binWidth = NA,
        ..binLowerLimit = NA)
)

flexhistResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "flexhistResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Flexible histogram")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=500,
                height=500,
                renderFun=".plot"))}))

flexhistBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "flexhistBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "flexhist",
                name = "flexhist",
                version = c(1,0,0),
                options = options,
                results = flexhistResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Flexible histogram
#'
#' 
#' @param data .
#' @param dep .
#' @param binWidthType .
#' @param binWidth .
#' @param binLowerLimit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the histogram \cr
#' }
#'
#' @export
flexhist <- function(
    data,
    dep,
    binWidthType = "default",
    binWidth = 0.5,
    binLowerLimit) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("flexhist requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- flexhistOptions$new(
        dep = dep,
        binWidthType = binWidthType,
        binWidth = binWidth,
        binLowerLimit = binLowerLimit)

    analysis <- flexhistClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

