
# This file is automatically generated, you probably don't want to edit this

ttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            alt = "notequal",
            varEq = TRUE, ...) {

            super$initialize(
                package="flexhist",
                name="ttest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..alt = NA,
        ..varEq = NA)
)

ttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        ttest = function() private$.items[["ttest"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="2 sample t-test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="2 sample t-test"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttest",
                title="Independent Samples T-Test",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Histogram",
                width=400,
                height=300,
                renderFun=".plot"))}))

ttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "flexhist",
                name = "ttest",
                version = c(1,0,0),
                options = options,
                results = ttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' 2 sample t-test
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param alt .
#' @param varEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ttest$asDF}
#'
#' \code{as.data.frame(results$ttest)}
#'
#' @export
ttest <- function(
    data,
    dep,
    group,
    alt = "notequal",
    varEq = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- ttestOptions$new(
        dep = dep,
        group = group,
        alt = alt,
        varEq = varEq)

    analysis <- ttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

